### ISSUE TITLE
1.0.7启用后，无法编写新文章

### ISSUE THREAD

**Issue by youlinstar** [gogobody/jkOptionsFramework#1]
报错
Return value of Typecho\I18n\GetText::translate() must be of the type string, null returned

编辑器为系统自带
没装其他插件，就装个jkOptionsFramework和jkSiteHelper

新增文章和编辑文章都会报错，禁用jkOptionsFramework就好了

**Comment by gogobody** [comment]
在config.inc.php里加入

define('__TYPECHO_DEBUG__', true);
开启下debug，给我一下具体报错行

**Comment by youlinstar** [comment]
> **TYPECHO_DEBUG** ', true);

![image](https://user-images.githubusercontent.com/94352609/178489564-8771ed52-63aa-4f9e-ada3-40c40cb13113.png)
就只有这样的报错

config.inc.php加过了

**Comment by gogobody** [comment]
TYPECHO_DEBUG前面和后面有两个下划线，`__TYPECHO_DEBUG__` 刚刚被和谐了

**Comment by youlinstar** [comment]
Return value of Typecho\I18n\GetText::translate() must be of the type string, null returned
TypeError: Return value of Typecho\I18n\GetText::translate() must be of the type string, null returned in /www/wwwroot/blog/var/Typecho/I18n/GetText.php:120
Stack trace:
#0 /www/wwwroot/blog/var/Typecho/I18n/GetTextMulti.php(57): Typecho\I18n\GetText->translate()
#1 /www/wwwroot/blog/var/Typecho/I18n.php(42): Typecho\I18n\GetTextMulti->translate()
#2 /www/wwwroot/blog/var/Typecho/Common.php(43): Typecho\I18n::translate()
#3 /www/wwwroot/blog/usr/themes/initial/functions.php(571): _t()
#4 /www/wwwroot/blog/var/Widget/Contents/Post/Edit.php(210): themeFields()
#5 /www/wwwroot/blog/admin/custom-fields.php(4): Widget\Contents\Post\Edit->getDefaultFieldItems()
#6 /www/wwwroot/blog/admin/write-post.php(53): include('/www/wwwroot/bl...')
#7 {main}

> TYPECHO_前面和后面有DE下面的GBU线，`__TYPECHO_DEBUG__`被抢先

**Comment by youlinstar** [comment]
> TYPECHO_前面和后面有DE下面的GBU线，`__TYPECHO_DEBUG__`被抢先

主题作者：http://www.offodd.com/

Initial
作者: [JIElive](http://www.offodd.com/)    版本: 2.5.2

**Comment by gogobody** [comment]
这是你的主题的问题，typecho 1.2版本改了`_t(xxx)`的用法，凡是遇到这种报错，就需要将对应行数将`_t()` 去掉即可，例如
`#3 /www/wwwroot/blog/usr/themes/initial/functions.php(571): _t()` 中，将这一行的 `_t(内容)` 外的`_t()` 去掉

**Comment by youlinstar** [comment]
> 这是你的主题的问题，typecho 1.2版本改了`_t(xxx)`的用法，凡是遇到这种报错，就需要将对应行数将`_t()` 去掉即可，例如 `#3 /www/wwwroot/blog/usr/themes/initial/functions.php(571): _t()` 中，将这一行的 `_t(内容)` 外的`_t()` 去掉

好的，谢谢
